week-04/programmer-fox-club/FoxPet/FoxPet/Models/Fox.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoxPet.Models
{
    public class Fox
    {
        public string Name { get; set; }
        public List<string> Tricks { get; set; }
        public string Food { get; set; }
        public string Drink { get; set; }
    }
}

week-04/programmer-fox-club/FoxPet/FoxPet/Controllers/FoxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FoxPet.Controllers
{
    public class FoxController : Controller
    {
        
    }
}

week-04/programmer-fox-club/FoxPet/FoxPet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FoxPet.Models;
using FoxPet.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.ExpressionTranslators.Internal;

namespace FoxPet.Controllers
{
    public class HomeController : Controller
    {
        private readonly IFoxServices FoxServices;

        public HomeController()
        {
            FoxServices = new FoxServices();
        }

        [HttpGet("/")]
        public IActionResult Information(string name)
        {
            if (name == null)
            {
                return RedirectToAction("Login");
            }
            
            var currentFox = FoxServices.Find(name);

            return View(currentFox);
        }

        [HttpGet("/login")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost("/login")]
        public IActionResult Login(string name)
        {
            if (name == null)
            {
                return RedirectToAction("Login");
            }
            else if (!FoxServices.Contains(FoxServices.Find(name)))
            {
                FoxServices.Add(name);
                return RedirectToAction("Login");
            }

            return RedirectToAction("Information", new { name = name });
        }
    }
}

week-04/programmer-fox-club/FoxPet/FoxPet/Views/Fox/NutritionStore.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using FoxPet.Models
@model Fox
@{
    ViewBag.Title = "NutritionStore";
}

<ul>
    <li><a href="/?name=@Model.Name">Information</a></li>
    <li><a hred="">Nutrition Store</a></li>
    <li><a href="trickCenter?name=@Model.Name">Trick Center</a></li>
    <li><a href="actionHistory?name=@Model.Name">Action History</a></li>
</ul>

<form asp-controller="Fox" asp-action="NutritionStore" method="post">
    Food 
    <select>
        @foreach (var food in @Model.Food)
        {
            <option value="Food">@food</option>
        }
    </select>

    Drink 
    <select>
        @foreach (var drink in @Model.Drink)
        {
            <option value="Drink">@drink</option>
        }
    </select>
    <button type="submit">Change</button>
</form>

week-04/programmer-fox-club/FoxPet/FoxPet/Views/Fox/TrickCenter.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using FoxPet.Models
@model Fox
@{
    ViewBag.Title = "TrickCenter";
}

<ul>
    <li><a href="/?name=@Model.Name">Information</a></li>
    <li><a href="nutritionStore?name=@Model.Name">Nutrition Store</a></li>
    <li><a href="trickCenter?name=@Model.Name">Trick Center</a></li>
    <li><a href="actionHistory?name=@Model.Name">Action History</a></li>
</ul>

<form asp-controller="Fox" asp-action="TrickCenter" method="post">
    Tricks <input type="text" name="Tricks" />
    <button type="submit">Learn</button>
</form>